language: node_js
node_js:
- "8"
- "10"
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run build
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
deploy:
  provider: npm
  skip_cleanup: true
  email: denisnikulin@gmail.com
  api_key:
    secure: vuaFHgXuq48pRlweCAdJ2L7/9sv/QoxHEPenBJPOo60Hi23GHuHXQjXdlegEaaDpZDPQdkB3FtslRlMci8SrJ5vlLzi/0UPRqm8t5BIALUW704yJ64eaPuE1Y6fviS5VPXRbbdEFAl5QRWgL+DHrra4NBQhzq3oWMXiTmTXSJdxvr37l5JLcpVrh6zWpPSAuxXu7hkdRp04NzttQreci7FA4hweVR7nqqpVKgAhmUKjNhkizt7ytiyoBq1taLcohd7AcW8jaxVbvL2dzTLZj7uREYKBBb7A+2wcKGAOxEdiP7vr3G/b03qps+I6sl1iv7U9IG9P5lh7PWmjv1uEicwvWrH+CpW50U/vkI9Batu6bTLxdIJjt1I8eL/kOH8DV+ZPEIpZjm5/3Z30fRhbv4KiiS8V0tfsz9AhniPvgZkLJ/kQSHjUkVMIIMp+XzGkEW13D8QUT56oR73TCy3nDV7k5tGJWlFjrsqudZ4H5iYThTZv1GoFf4DLd3o1V/y3QimMa44pmLxanlGep2EDJ+oZinsZC+pDN6bU9UCqOy0LMGfcMhF0tFZbLAdN5qzFVNFMWKKE5BxkGaRA3H4R930h2AZcEF/e2jLnYoHkAhHkjhXGfAXSXLp6pr1ZVmZU85IOPiNFTwnnUakuPPVE12oM8Ssxcyr7Ka3pX6GziaRo=
  on:
    tags: true
